export default {
    SET_FILTERS: 'SET_FILTERS',
    SET_CART_RESTAURANT: 'SET_CART_RESTAURANT',
    SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
    SET_CART_BADGE: 'SET_CART_BADGE',
    SET_CART_TOAST: 'SET_CART_TOAST'
}